# Generated by Django 5.2.13 on 2026-04-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_editora_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editora',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='editora',
            name='email',
        ),
    ]
