# Generated by Django 5.2.13 on 2026-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
