# Generated by Django 5.2.13 on 2026-09-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_compra_tipo_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='compra',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
