# Generated by Django 5.2.13 on 2026-09-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_data_compra_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscompra',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='core.livro'),
        ),
    ]
